### ISSUE TITLE
Grab building and unit info from game

### ISSUE THREAD

**Issue by veger** [veger/foei#12]
So it is not needed to create a list of building and unit ids anymore *and* they can be localized in the games language (easier to recognize the buildings)

**Comment by veger** [comment]
I was planning this for a while already (then the provided metadata + code to access it changed), so I never got to it.

@paskyorg started working on it: https://github.com/paskyorg/foei

**Comment by paskyorg** [comment]
Yes, I was coding the metadata, but I had some problems with the language, since it has to be done for multiple languages. I hope finish it soon.

**Comment by veger** [comment]
It might be interesting to check out the `StaticDataService.getMetadata` response (you get it if the game (re)loads).
It contains all metadata files for that specific server/language. So they can be easily obtained and should match.
Using the hash it is even possible to cache it locally and only download when changed.

At least this was my plan for when I would implement this

**Comment by paskyorg** [comment]
Take a look at this. Maybe it works for you.
https://github.com/paskyorg/foei/commit/c87aa783f3a155c2080d0eaf90d7da6cbb06e20a

**Comment by veger** [comment]
ok, thanks. I'l l take a look as soon as I have some spare time!

**Comment by veger** [comment]
Implemented by v0.6.0
