### ISSUE TITLE
Show owned goods when plundering

### ISSUE THREAD

**Issue by veger** [veger/foei#2]
It would be nice to show the amount of goods the player already owns when plundering.
This helps choosing which building to plunder.

**Comment by Osiris556** [comment]
When plundering I always just choose which goods are going to benefit myself the most. The ammount of goods they player needs or dosnt need seems irrelevant

**Comment by Osiris556** [comment]
Is it possible to see who a player has on their friends list?

**Comment by veger** [comment]
No, you cannot see the friends of a player (AFAIK), but you can go the their tavern and take a look who is inside (it is an incomplete list thought...)

Attack and defend boost are shown (after you attacked them at least once, because this information is presented when attacking someone).

* 1 def is 30% defense boost
* 1 atk is 30% attack boost

(Maybe I should just show the numbers, instead of taking steps of 30%, it is something I did when I was manually keeping track of these statistics... :wink: )

This player for example has between 30% and 60% defense boost: 
![1def](https://user-images.githubusercontent.com/171827/55289899-9cc37600-53cc-11e9-9809-f3d7d0134940.png)

**Comment by veger** [comment]
> It would be nice to show the amount of goods the player already owns when plundering.

Even better: also (secondary) order on the amount of goods if value is the same
