### ISSUE TITLE
code not checking for the existence of armyDetails.battles

### ISSUE THREAD

**Issue by rdemetrescu** [veger/foei#22]
I always see this message on chrome extension Error details for FoEI 0.6.0:

`Error handling response: TypeError: Cannot read property 'details' of undefined`

on this line of code:

`      let details = armyDetails.battles.details.pop()`

And here is the presented stack trace:

``` 
background/battle_field.js:171 (anonymous function)
background/storage.js:133 (anonymous function)
```

**Comment by veger** [comment]
I was not able to reproduce. This error should only be possible if (somehow) you managed to end a battle without starting it...
Nonetheless I added checks to detect if the 'battle details' object is defined or not

**Comment by veger** [comment]
It has been a while and not response, so I am guessing the issue got solved?
